# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: luz_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: luz_db
    ports:
      - "5432:5432"
    volumes:
      - luz_db_data:/var/lib/postgresql/data
volumes:
  luz_db_data:
